version: "3"
services:
  package:
    image: registry.gitlab.com/aplus-framework/images/package
    container_name: package-one
    working_dir: /package
    volumes:
      - .:/package
    tty: true
